---
title: "Add time prefix to files"
author: "Lochlin Ermatinger"
date: '2022-04-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# This script is not constrained to the .asd file format. 
# It can be used to change the filenames of any data format so long as they are all stored in the same location.  

fileStorage <- "C:\\Users\\lochl\\OneDrive\\Desktop\\Sawfly Lab\\ASD\\2022\\Leaf\\LB\\DC2.5.5.22\\Processed\\" #Folder location of files.

fileNames <- list.files(fileStorage) 

#fileNames <- toupper(fileNames) # If file name is not already capitalized unhash and run this line.

################ Only use this chunk to take out Z values that look like this (t2LBC1+5900000.asd.txt)###########
#fileNameDups <- fileNames
#substr(fileNameDups,7,9) <- "   " 
#fileNameDups <- fileNameDups %>% gsub(pattern = "[[:space:]]", replacement = "")
#################################################################################################################

################ Only use this code if your data extends to "t10"
################ Use this function to add a "0" so the time format is consistent.
################ i.e. "t1" to "t01"

#newFileNames <- gsub(fileNames, pattern = "(.{1})(.*)", replacement = "\\10\\2")
#################################################################

filePrefix = function(files,prefixes) {      
  output <- paste(prefixes,files,sep = "")
  return(output)
}

newFileNames <- filePrefix(fileNames,"x") #Replace 'x' with desired time prefix.
#newFileNames <- filePrefix(fileNameDups,"") # unhash and use this if you are getting rid of Z values

file.rename(paste0(fileStorage,fileNames),
            paste0(fileStorage,newFileNames)) #Existing files will be renamed with this output. you can change the location of the output by specifying a different folder where the second 'fileStorage' is called.

```


